# Generated by Django 4.2.15 on 2024-08-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountValue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
