# Generated by Django 4.2.15 on 2024-08-28 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_discountvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountValue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='put discount value', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=100.0, help_text='this is the price if no discount, if is discount it become an old price'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='description')),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
        ),
    ]
