# Generated by Django 4.2.15 on 2024-08-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_proimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proimage',
            options={'verbose_name': 'Product images', 'verbose_name_plural': 'Product Images'},
        ),
    ]
