# Generated by Django 4.2.15 on 2024-08-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='cartitems',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='quantity_positive'),
        ),
    ]
