# Generated by Django 4.2.15 on 2024-08-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customers', 'verbose_name_plural': 'Customers'},
        ),
    ]
